"""Filter-chain conf body generator for Output plugin inserts.

PipeWire's module-filter-chain takes an SPA-JSON-ish conf describing
its capture/playback streams and the plugin graph. We generate one
conf per Output with an enabled PluginInsert. The chain captures
from `phonon_master` (sink-capture: reads what's been written to the
master null-sink) and plays into the output's actual sink. The
plugin sits in between.

Kept as a separate module so the body is unit-testable without a
PipeWire backend in the loop — and so the same generator drives the
Fake backend (which records the body string) and the Real one
(which writes it to disk).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from phonon_stage.mixer.models import Output, PluginInsert

# Chain identity helpers. The chain name doubles as the PipeWire
# node.name and the conf file's basename, so the rest of the system
# can find the chain by output id alone.
CHAIN_NAME_PREFIX = "phonon_fx_"


def chain_name_for(output: Output) -> str:
    """Stable PW node name for the chain. Tied to the output id, not
    to the underlying sink — keeps the name constant if the user
    repoints the output to a different sink (e.g. DG60 #1 → DG60 #2)."""
    return f"{CHAIN_NAME_PREFIX}{output.id}"


def render_filter_chain_conf(output: Output, insert: PluginInsert, master_sink_name: str) -> str:
    """Produce the conf body for one Output's filter-chain.

    Format: PipeWire's context.modules conf array, with one
    libpipewire-module-filter-chain entry. SPA-JSON-ish — uses `=`
    not `:`, key-value pairs separated by whitespace, no commas.

    The `control` dict carries every plugin control we know about.
    Names are quoted because LSP uses names with spaces and special
    chars (e.g. "Time (ms)", "Dry/Wet balance (%)").
    """
    controls_body = _render_controls(insert.controls)
    chain = chain_name_for(output)
    description = f"Phonon FX — {output.label or output.sink_node_name}"
    # Indented for human readability; PW's spa-json parser is
    # whitespace-insensitive.
    return f"""# Generated by phonon-stage. Do not edit by hand —
# changes are overwritten on the next mixer reconcile.
context.modules = [
  {{ name = libpipewire-module-filter-chain
    flags = [ nofail ]
    args = {{
      node.name = {chain}
      node.description = "{description}"
      media.name = "{description}"
      filter.graph = {{
        nodes = [
          {{
            type = {insert.backend}
            name = fx
            plugin = "{insert.library}"
            label = "{insert.label}"
            control = {{
{controls_body}
            }}
          }}
        ]
      }}
      audio.channels = 2
      audio.position = [ FL FR ]
      capture.props = {{
        node.target = {master_sink_name}
        stream.capture.sink = true
      }}
      playback.props = {{
        node.target = "{output.sink_node_name}"
      }}
    }}
  }}
]
"""


def _render_controls(controls: dict[str, float]) -> str:
    """Render a {name → value} dict as SPA-JSON `key = value` lines.
    Names with spaces or special chars get quoted; bare-word safe
    names don't, to keep the conf readable for the LADSPA-savvy
    operator skimming the file."""
    lines: list[str] = []
    for name in sorted(controls.keys()):  # deterministic order — easier diffs
        value = controls[name]
        key = _quote_key_if_needed(name)
        lines.append(f"              {key} = {_render_value(value)}")
    return "\n".join(lines)


def _quote_key_if_needed(name: str) -> str:
    if name.isidentifier():
        return name
    # Escape embedded quotes defensively even though LSP labels don't
    # contain them today — cheap and future-proof.
    safe = name.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{safe}"'


def _render_value(value: float) -> str:
    """Render a control value as bare numeric. PW accepts integers
    without a decimal point and treats toggles as 0/1, so we drop
    the trailing `.0` on whole numbers for a less noisy conf file."""
    f = float(value)
    if f.is_integer():
        return str(int(f))
    return repr(f)
