#!/usr/bin/env bash
# install-dev-sudoers.sh — grant a single user the same NOPASSWD systemctl
# rights that install.sh gives to the phonon daemon user. Use this on a
# dev workstation where you run the daemon under your normal account
# (e.g. `sam`) instead of going through the full install.sh.
#
#   sudo bash deploy/install-dev-sudoers.sh           # uses $SUDO_USER
#   sudo bash deploy/install-dev-sudoers.sh alice     # explicit user
#
# Drops /etc/sudoers.d/phonon-dev. Re-runnable. Validates with visudo -c
# before installing — refuses to write a broken sudoers file.

set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
    echo "Re-running under sudo..." >&2
    exec sudo -E bash "$0" "$@"
fi

USER_NAME="${1:-${SUDO_USER:-}}"
if [ -z "${USER_NAME}" ] || ! id -u "${USER_NAME}" >/dev/null 2>&1; then
    echo "Usage: sudo $0 [username]" >&2
    echo "  No user given and \$SUDO_USER is empty or invalid." >&2
    exit 1
fi

OUT="/etc/sudoers.d/phonon-dev"
TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

# Write rules for every path systemctl might resolve to. On usrmerged
# distros (Ubuntu 24.04, Pi OS Bookworm, etc.) /bin -> /usr/bin so both
# refer to the same file, but sudo's path matching is literal — if the
# user types `systemctl …` and PATH lookup yields /usr/bin/systemctl, a
# rule keyed on /bin/systemctl won't match.
SYSTEMCTL_PATHS=("/usr/bin/systemctl" "/bin/systemctl")

emit_rule() {
    # $1 = full sudoers spec after "NOPASSWD: " (without the path prefix)
    for p in "${SYSTEMCTL_PATHS[@]}"; do
        echo "${USER_NAME} ALL=(ALL) NOPASSWD: ${p} $1"
    done
}

{
    cat <<HEADER
# Auto-generated by deploy/install-dev-sudoers.sh — grants ${USER_NAME}
# the same NOPASSWD rights as the phonon daemon user. Safe to delete.
${USER_NAME} ALL=(ALL) NOPASSWD: /usr/sbin/rfkill
${USER_NAME} ALL=(ALL) NOPASSWD: /usr/bin/rfkill
${USER_NAME} ALL=(ALL) NOPASSWD: /usr/sbin/hciconfig
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/hciconfig
${USER_NAME} ALL=(ALL) NOPASSWD: /usr/local/sbin/phonon-update
HEADER
    emit_rule "is-active *"
    CONTROLLABLE=(
        bluetooth bluealsa avahi-daemon
        phonon-bt-agent phonon-bt-unblock
        phonon-ptp4l phonon-phc2sys
    )
    for verb in start stop restart enable disable; do
        for svc in "${CONTROLLABLE[@]}"; do
            emit_rule "${verb} ${svc}.service"
        done
    done
} > "${TMP}"

chmod 0440 "${TMP}"
if ! visudo -c -f "${TMP}" >/dev/null; then
    echo "ERROR: generated sudoers file failed visudo validation" >&2
    exit 2
fi

install -m 0440 -o root -g root "${TMP}" "${OUT}"
echo "Installed ${OUT} for user '${USER_NAME}'."
echo "Try: sudo -n -u ${USER_NAME} systemctl is-active bluetooth"
