#!/usr/bin/env bash
# Phonon Stage Agent — install script (multi-arch, idempotent)
# Usage:
#   sudo bash install.sh                          # default: stage-only
#   sudo bash install.sh --role=stage-only        # explicit stage
#   sudo bash install.sh --role=controller-only   # controller only (future)
set -euo pipefail

# ── Constants ───────────���────────────────────────────────────────────────

PHONON_USER="phonon"
PHONON_GROUP="phonon"
INSTALL_DIR="/opt/phonon/stage"
VENV_DIR="${INSTALL_DIR}/.venv"
CONFIG_DIR="/etc/phonon"
DATA_DIR="/var/lib/phonon"
LOG_DIR="/var/log/phonon"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
STAGE_SRC="${REPO_ROOT}/stage"

# ── Argument parsing ─────────────────────────────────────────────────────

ROLE="stage-only"

for arg in "$@"; do
    case "$arg" in
        --role=*) ROLE="${arg#*=}" ;;
        --help|-h)
            echo "Usage: sudo bash install.sh [--role=stage-only|controller-only]"
            exit 0
            ;;
        *)
            echo "[ERROR] Unknown argument: $arg"
            exit 1
            ;;
    esac
done

# ── Checks ────────────���─────────────────────────────���────────────────────

if [ "$(id -u)" -ne 0 ]; then
    echo "[ERROR] This script must be run as root (sudo)"
    exit 1
fi

# ── Step 1/7: Detect architecture and distro ─────────────────────────────

echo "[1/7] Detecting platform..."

ARCH=$(uname -m)
case "$ARCH" in
    x86_64)  PLATFORM="x86_64" ;;
    aarch64) PLATFORM="arm64" ;;
    *)
        echo "[ERROR] Unsupported architecture: $ARCH"
        exit 1
        ;;
esac

if [ -f /etc/os-release ]; then
    . /etc/os-release
    DISTRO="${ID:-unknown}"
    DISTRO_VERSION="${VERSION_ID:-unknown}"
else
    echo "[ERROR] Cannot detect distribution (/etc/os-release missing)"
    exit 1
fi

echo "  Platform: ${PLATFORM} | Distro: ${DISTRO} ${DISTRO_VERSION}"

# ── Step 2/7: Install system dependencies ────────���───────────────────────

echo "[2/7] Installing system dependencies..."

apt-get update -qq
apt-get install -y -qq \
    python3-venv \
    python3-dev \
    libdbus-1-dev \
    pkg-config \
    avahi-daemon \
    pipewire \
    pipewire-alsa \
    pipewire-pulse \
    wireplumber \
    2>/dev/null

echo "  System packages OK"

# ── Step 3/7: Create phonon user ──────────���─────────────────────────────

echo "[3/7] Creating phonon user..."

if id -u "${PHONON_USER}" &>/dev/null; then
    echo "  User ${PHONON_USER} already exists"
else
    useradd -r -s /usr/sbin/nologin -d /nonexistent "${PHONON_USER}"
    echo "  User ${PHONON_USER} created"
fi

# Add to audio + bluetooth groups
usermod -aG audio "${PHONON_USER}" 2>/dev/null || true
usermod -aG bluetooth "${PHONON_USER}" 2>/dev/null || true
echo "  User in audio + bluetooth groups"

# Install D-Bus policy for BlueZ access
if [ -f "${SCRIPT_DIR}/dbus/phonon-bluetooth.conf" ]; then
    cp "${SCRIPT_DIR}/dbus/phonon-bluetooth.conf" /etc/dbus-1/system.d/
    echo "  D-Bus BlueZ policy installed"
fi

# ── Step 4/7: Create directories ────────────────────────────────────────

echo "[4/7] Creating directories..."

mkdir -p "${CONFIG_DIR}" "${DATA_DIR}" "${LOG_DIR}" "${INSTALL_DIR}"
chown "${PHONON_USER}:${PHONON_GROUP}" "${DATA_DIR}" "${LOG_DIR}"
chmod 0750 "${DATA_DIR}"
chmod 0755 "${LOG_DIR}" "${CONFIG_DIR}"

echo "  Directories OK"

# ── Step 5/7: Python venv + install package ──────────────────────────────

echo "[5/7] Setting up Python venv and installing phonon-stage..."

if [ ! -d "${VENV_DIR}" ]; then
    python3 -m venv "${VENV_DIR}"
    echo "  venv created"
else
    echo "  venv already exists"
fi

"${VENV_DIR}/bin/pip" install --upgrade pip --quiet
"${VENV_DIR}/bin/pip" install "${STAGE_SRC}" --quiet

echo "  phonon-stage installed"

# ── Step 6/7: Generate config if absent ──────────────────────────────────

echo "[6/7] Generating config..."

if [ ! -f "${CONFIG_DIR}/stage.yaml" ]; then
    # Detect primary IP address
    BIND_IP=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' || echo "127.0.0.1")

    cat > "${CONFIG_DIR}/stage.yaml" <<YAML
# Phonon Stage Agent configuration
# Generated by install.sh on $(date -Iseconds)
bind_address: "${BIND_IP}"
port: 8401
log_level: "INFO"
YAML

    chown "${PHONON_USER}:${PHONON_GROUP}" "${CONFIG_DIR}/stage.yaml"
    chmod 0640 "${CONFIG_DIR}/stage.yaml"
    echo "  Config generated (bind_address: ${BIND_IP})"
else
    echo "  Config already exists, not overwriting"
fi

# ─�� Step 7/7: Install and start systemd service ─────────────────────────

echo "[7/7] Installing systemd service..."

cp "${SCRIPT_DIR}/systemd/phonon-stage.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable phonon-stage.service --quiet

echo "  Starting phonon-stage..."
systemctl restart phonon-stage.service

# Brief pause to let the service start
sleep 1

if systemctl is-active --quiet phonon-stage.service; then
    echo ""
    echo "========================================="
    echo "  Phonon Stage Agent installed and running"
    echo "  Platform: ${PLATFORM} (${DISTRO} ${DISTRO_VERSION})"
    echo "  Config:   ${CONFIG_DIR}/stage.yaml"
    echo "  Logs:     journalctl -u phonon-stage -f"
    echo "========================================="
else
    echo ""
    echo "[WARNING] Service installed but not running. Check:"
    echo "  journalctl -u phonon-stage -e --no-pager"
    exit 1
fi
