#!/usr/bin/env bash
# install-dev-sudoers.sh — grant a single user the same NOPASSWD systemctl
# rights that install.sh gives to the phonon daemon user. Use this on a
# dev workstation where you run the daemon under your normal account
# (e.g. `sam`) instead of going through the full install.sh.
#
#   sudo bash deploy/install-dev-sudoers.sh           # uses $SUDO_USER
#   sudo bash deploy/install-dev-sudoers.sh alice     # explicit user
#
# Drops /etc/sudoers.d/phonon-dev. Re-runnable. Validates with visudo -c
# before installing — refuses to write a broken sudoers file.

set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
    echo "Re-running under sudo..." >&2
    exec sudo -E bash "$0" "$@"
fi

USER_NAME="${1:-${SUDO_USER:-}}"
if [ -z "${USER_NAME}" ] || ! id -u "${USER_NAME}" >/dev/null 2>&1; then
    echo "Usage: sudo $0 [username]" >&2
    echo "  No user given and \$SUDO_USER is empty or invalid." >&2
    exit 1
fi

OUT="/etc/sudoers.d/phonon-dev"
TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

cat > "${TMP}" <<SUDOERS
# Auto-generated by deploy/install-dev-sudoers.sh — grants ${USER_NAME}
# the same NOPASSWD rights as the phonon daemon user. Safe to delete.
${USER_NAME} ALL=(ALL) NOPASSWD: /usr/sbin/rfkill
${USER_NAME} ALL=(ALL) NOPASSWD: /usr/bin/rfkill
${USER_NAME} ALL=(ALL) NOPASSWD: /usr/sbin/hciconfig
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/hciconfig
${USER_NAME} ALL=(ALL) NOPASSWD: /usr/local/sbin/phonon-update
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl is-active *
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl start bluetooth.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl stop bluetooth.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl restart bluetooth.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl start bluealsa.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl stop bluealsa.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl restart bluealsa.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl start avahi-daemon.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl stop avahi-daemon.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl restart avahi-daemon.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl start phonon-bt-agent.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl stop phonon-bt-agent.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl restart phonon-bt-agent.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl start phonon-bt-unblock.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl stop phonon-bt-unblock.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl restart phonon-bt-unblock.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl start phonon-ptp4l.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl stop phonon-ptp4l.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl restart phonon-ptp4l.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl enable phonon-ptp4l.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl disable phonon-ptp4l.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl start phonon-phc2sys.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl stop phonon-phc2sys.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl restart phonon-phc2sys.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl enable phonon-phc2sys.service
${USER_NAME} ALL=(ALL) NOPASSWD: /bin/systemctl disable phonon-phc2sys.service
SUDOERS

chmod 0440 "${TMP}"
if ! visudo -c -f "${TMP}" >/dev/null; then
    echo "ERROR: generated sudoers file failed visudo validation" >&2
    exit 2
fi

install -m 0440 -o root -g root "${TMP}" "${OUT}"
echo "Installed ${OUT} for user '${USER_NAME}'."
echo "Try: sudo -n -u ${USER_NAME} systemctl is-active bluetooth"
