#!/usr/bin/env bash
# phonon-nqptp — privileged helper for nqptp interface binding.
#
# nqptp's `-i <iface>` flag pins its UDP 319/320 listener to a
# single interface. Default (no flag) is to listen on every iface,
# which is usually what you want for AirPlay 2 — but on multi-NIC
# stages, the audio iface and the management iface differ, and
# putting nqptp on the wrong one breaks AP2 discovery.
#
# We don't edit /etc/systemd/system/nqptp.service directly — that's
# managed by install.sh (copied from deploy/systemd/). Instead we
# write a drop-in at /etc/systemd/system/nqptp.service.d/phonon-iface.conf
# that overrides just ExecStart. Drop-ins are the canonical way to
# extend a unit without losing track of upstream changes.
#
# Subcommands:
#   set-iface <iface>     install drop-in with `-i <iface>`, reload + restart
#   clear-iface           remove drop-in (back to default: listen all), reload + restart

set -euo pipefail

DROPIN_DIR=/etc/systemd/system/nqptp.service.d
DROPIN_FILE="${DROPIN_DIR}/phonon-iface.conf"
LOG=/var/log/phonon/nqptp.log
NQPTP_BIN=/usr/local/bin/nqptp

mkdir -p "$(dirname "$LOG")"

log() {
    echo "[$(date -Iseconds)] $*" | tee -a "$LOG"
}

# Refuse iface names that contain anything other than [A-Za-z0-9._-].
# Linux iface name max length is 15 — anything longer is malformed.
validate_iface() {
    local name="$1"
    if [ -z "$name" ]; then
        log "set-iface: empty iface — refusing"
        return 2
    fi
    if [ "${#name}" -gt 15 ]; then
        log "set-iface: iface too long (>15 chars): $name"
        return 2
    fi
    if ! [[ "$name" =~ ^[A-Za-z0-9._-]+$ ]]; then
        log "set-iface: invalid chars in iface: $name"
        return 2
    fi
}

reload_and_restart_if_active() {
    systemctl daemon-reload
    if systemctl is-active --quiet nqptp.service; then
        systemctl restart nqptp.service
        log "nqptp restarted (was active)"
    else
        log "nqptp not active — skipping restart (next start picks up the new drop-in)"
    fi
}

cmd_set_iface() {
    local iface="$1"
    validate_iface "$iface"
    if [ ! -x "$NQPTP_BIN" ]; then
        log "set-iface: nqptp not installed at ${NQPTP_BIN} — refusing"
        return 3
    fi
    mkdir -p "$DROPIN_DIR"
    # Atomic write: tempfile + rename so systemd never reads a partial
    # file (it does aggressive caching off mtime).
    local tmp
    tmp="$(mktemp --tmpdir="$DROPIN_DIR" phonon-iface.XXXXXX)"
    cat > "$tmp" <<EOF
# Generated by phonon-stage. Pins nqptp to a specific interface.
# Edits made by hand will be overwritten on the next settings change.
[Service]
ExecStart=
ExecStart=${NQPTP_BIN} -i ${iface}
EOF
    chmod 0644 "$tmp"
    mv -f "$tmp" "$DROPIN_FILE"
    log "set-iface: bound nqptp to ${iface} via drop-in"
    reload_and_restart_if_active
}

cmd_clear_iface() {
    if [ -f "$DROPIN_FILE" ]; then
        rm -f "$DROPIN_FILE"
        log "clear-iface: removed drop-in (nqptp will listen on all ifaces)"
    else
        log "clear-iface: no drop-in to remove — noop"
    fi
    reload_and_restart_if_active
}

case "${1:-}" in
    set-iface)
        shift
        cmd_set_iface "${1:-}"
        ;;
    clear-iface)
        cmd_clear_iface
        ;;
    *)
        echo "usage: $0 {set-iface <iface> | clear-iface}" >&2
        exit 1
        ;;
esac
